name: macOS_py310_x64 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  macOS_py310_x64:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true # fail-fast: true meant that if one test fail, then all running tests will be canceled
      matrix:
        config:
        - { name: "macOS (py310_x64)", os: macos-latest, python-version: '3.10', architecture: x64, artifact_name: "macos-latest.py310_x64.whl.zip" }

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.config.python-version }}
        architecture: ${{ matrix.config.architecture }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel flake8 pytest twine isort build pybind11==2.11

    - name: Build package (setup.py)
      run: |
        python -m build --wheel

    - name: Install package (dist/*.whl)
      run: |
        python util_funcs.py --func="install_dist" --pat="dist/**/*.whl" --pkg_name="actions_python_cpp_compiler"

    - name: Test with builtin test function
      run: |
        python -c "import actions_python_cpp_compiler; actions_python_cpp_compiler.run_tests()"

    - name: Twine check
      if: ${{ always() }}
      run: |
        twine check dist/*

    - name: Upload wheel artifact
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.artifact_name }}
        path: dist/*.whl
