name: Ubuntu (tests) 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre_test_ubuntu:
    # test build only on one config, if all ok, then run almost the same steps on other configs
    # some test could be run only once (isort, flake8)
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true # fail-fast: true meant that if one test fail, then all running tests will be canceled
      matrix:
        config:
        - { name: "pre_test Ubuntu (py310_x64)", os: ubuntu-latest, python-version: '3.10', architecture: x64 }

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.config.python-version }}
        architecture: ${{ matrix.config.architecture }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel flake8 pytest twine isort pybind11==2.10.0

    - name: Build package (setup.py)
      run: |
        python setup.py build --build-lib=lib bdist_wheel

    - name: Install package (dist/*.whl)
      run: |
        python util_funcs.py --func="install_dist" --pat="dist/**/*.whl" --pkg_name="actions_python_cpp_compiler"

    - name: Test with builtin test function
      run: |
        python -c "import actions_python_cpp_compiler; actions_python_cpp_compiler.run_tests()"

    - name: Lint with isort
      if: ${{ always() }}
      run: |
        isort --diff pkg/python setup.py util_funcs.py
        isort --check-only pkg/python setup.py util_funcs.py

    - name: Lint with flake8
      if: ${{ always() }}
      run: |
        # autopep8 --aggressive --aggressive --aggressive --recursive --in-place pkg/python setup.py util_funcs.py
        flake8 --count --max-complexity=10 --statistics pkg/python setup.py util_funcs.py

    - name: Twine check
      if: ${{ always() }}
      run: |
        twine check dist/*
