name: Upload to PIP (pypi.org)

on:
  workflow_call:
    secrets:
      PYPI_USERNAME_TOKEN_PROD:
        required: true
      PYPI_PASSWORD_TOKEN_PROD:
        required: true
      PYPI_URL_PROD:
        required: true
  workflow_dispatch:

jobs:
  upload_to_prod:
    if: startsWith(github.ref, 'refs/tags/v')
    name: "pypi.org"
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'false'
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Copy whl files into dist folder
      run: |
        python util_funcs.py --func=copyfiles --pat=artifacts/**/*.whl --dest_to=dist

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U twine

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME_TOKEN_PROD }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD_TOKEN_PROD }}
      run: |
        twine upload --skip-existing --non-interactive --verbose --repository-url ${{ secrets.PYPI_URL_PROD }} dist/*
        # twine upload --skip-existing --non-interactive --verbose --repository-url https://pypi.org/legacy/ dist/*
